services:
  node-server:
    # image: node:18.20.3 if create a new container, but if you have dockerfile do this
    build:
      context: ./authorizetion
      dockerfile: Dockerfile.server
    container_name: mynode
#   volumes:
    environment:
      - author=Artem
    ports:
      - 1234:1234 #server
      - 4001:4001 #metric server
      - 9090:9090 #prometheus
     
  
  push-notifier:
    build: 
      context: ./push-notifice
      dockerfile: Dockerfile.push
    container_name: push-notifier
    ports:
      - 9123:9123
    depends_on:
      - node-server  